alphagov/packager

fpm/recipes/gof3r/recipe.rb
This adds a gof3r recipe based upon the work in https://github.com/alphagov/packager/pull/111
=> Gof3r recipe

fpm/recipes/terraform/recipe.rb
We need this for some S3/Lambda resources.
=> Upgrade Terraform to 0.6.15

fpm/recipes/etcd/recipe.rb, fpm/recipes/etcd/upstart-etcd.conf
Initial pass at an fpm-cookery package script for etcd.
=> Add etcd fpm cookery build script.

fpm/recipes/terraform/recipe.rb
Upgraded Terraform to 0.7.7 to keep it up to date.
=> Upgrade Terraform to 0.7.7

fpm/recipes/terraform/recipe.rb
Upgraded Terraform to 0.7.9 to keep it up to date
https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#079-november-4-2016
=> Upgraded Terraform to 0.7.9

fpm/recipes/jenkins-agent/recipe.rb
Create a package to download and install the Jenkins Swarm plugin aka jenkins-agent
=> Add jenkins-agent

fpm/recipes/jenkins-agent/recipe.rb
I mistakenly admitted this which is required for the build to succeed.
EDIT: omitted, by I also admit it
=> Add destdir

fpm/recipes/terraform/recipe.rb
Upgrading the version number and sha256 hash to 0.8.0
=> Upgrading Terraform to 0.8.0

fpm/recipes/terraform/recipe.rb
Upgrading Terraform again due to a whitespace bug in 0.8.0
=> Upgrading Terraform to 0.8.1

fpm/recipes/statsd/post-install, fpm/recipes/statsd/post-uninstall, fpm/recipes/statsd/recipe.rb, fpm/recipes/statsd/statsd.config.js, fpm/recipes/statsd/statsd.service, fpm/recipes/statsd/statsd.upstart
This commit pinches the recipe built here: https://github.com/bernd/fpm-recipes/tree/master/statsd
This version is a couple of years old so may want to look at upgrading it to 0.8? Let me know if you want me to do the work around that.
=> Add statsd

fpm/.gitignore, fpm/README.md, fpm/Vagrantfile, fpm/provision.sh, fpm/recipes/locksmithctl/recipe.rb
This PR adds a fpm-cookery recipe to build [locksmithctl](https://github.com/coreos/locksmith) for xenial.
=> Xenial locksmithctl

fpm/recipes/sops/recipe.rb
We use sops to decrypt data we use in Terraform, and would like to use this package on a Jenkins instance.
https://trello.com/c/qAzTAU4p/952-build-box-spike-on-adding-tf-deploys-to-current-integration-carrenza-deploy-jenkins
=> Add sops recipe

fpm/recipes/gds-local-pip-10.0.1/recipe.rb, fpm/recipes/gds-local-python-2.7.14/recipe.rb, fpm/recipes/gds-local-setuptools-39.0.1/recipe.rb
- Underscores are a no no
@schmie
=> Fix naming scheme for gds local python package names

fpm/recipes/gdal/recipe.rb
=> Add GDAL (1.11.5) recipe

fpm/recipes/ruby-2.6.1/recipe.rb
This will allow us to run apps using the latest version of Ruby.
=> Add recipe for Ruby 2.6.1

fpm/recipes/ruby-2.6.2/recipe.rb
This is based on the recipe file for Ruby 2.6.1.
[Trello Card](https://trello.com/c/HgcuyAyI/945-upgrade-to-ruby-262)
=> Add Ruby 2.6.2

fpm/recipes/ruby-2.6.3/recipe.rb
This is based on the recipe file for Ruby 2.6.2.
[Trello Card](https://trello.com/c/HgcuyAyI/945-upgrade-to-ruby-262)
=> Add Ruby 2.6.3

fpm/recipes/terraform/recipe.rb
https://github.com/hashicorp/terraform/blob/v0.11/CHANGELOG.md#01114-may-16-2019
=> Upgrade the Terraform package to 0.11.14

fpm/recipes/statsd/recipe.rb, fpm/recipes/statsd/statsd.service
Update thestatsd recipe to support the latest version.
=> Update statsd recipe

fpm/recipes/ruby-2.7.0/recipe.rb
- It was released on Christmas Day and we're upgrading all the apps to
be current.
- No idea how to test this given the instructions say the dev VM, but we
don't have that any more.
https://trello.com/c/XoJF36Pn/1663-8-upgrade-to-ruby-27
=> Add Ruby 2.7.0

fpm/recipes/ruby-2.6.6/recipe.rb
We need to document how to test this now that the dev VM is gone, if anybody knows how.
---
[Trello card](https://trello.com/c/tUhr4Cw9/1885-3-upgrade-ruby-to-version-266-in-govuk-repos)
=> Add a recipe for ruby-2.6.6

fpm/recipes/govuk-python-3.6.12/recipe.rb
Add depends and configure params to fix issues running ckanext-datagovuk tests.
This has been manually tested on integration.
=> Update python 3.6.12 release

fpm/recipes/govuk-python3-3.6.12/recipe.rb
This will allow installation of a specific version of python 3 to be installed without affecting the govuk-python package already installed.
=> Add govuk-python3 package

fpm/recipes/ruby-2.7.3/recipe.rb
Docs: https://docs.publishing.service.gov.uk/manual/ruby.html#add-a-new-ruby-version-in-puppet
Trello card: https://trello.com/c/9jEm7dwr/775-make-a-gem-for-shared-personalisation-code
=> Add recipe for Ruby 2.7.3

fpm/recipes/ruby-2.6.9/recipe.rb, fpm/recipes/ruby-2.7.5/recipe.rb, fpm/recipes/ruby-3.0.3/recipe.rb, fpm/recipes/ruby-3.1.0/recipe.rb
[Trello](https://trello.com/c/ZMrLumn8/2837-upgrade-ruby-for-our-apps-5)
=> Add latest ruby versions
