- pkg/locksmithctl/debian/changelog
- pkg/locksmithctl/srcurl
Version 0.2.3 supports multiple endpoints for etcd.
This is my first commit to packager, so I've just copied prior art for doing this.
> [#88491012] Upgrade locksmith from 0.2.2 to 0.2.3

- pkg/goenv/debian/changelog
- pkg/goenv/debian/control
- pkg/goenv/debian/goenv.links
Some of the tools (eg goenv-install) assume that the bin dir will be
alongside the libexec dir.  This amends the install to create this dir
with the necessary symlink in it, in addition to the /usr/bin/goenv
symlink.
> [goenv] Add bin symlink alongside libexec dir

- pkg/grafana/debian/changelog
- pkg/grafana/srcurl
I've uploaded this package to Launchpad but it's not appearing yet: https://launchpad.net/~gds/+archive/ubuntu/govuk/+packages
```
Uploading to ppa (via ftp to ppa.launchpad.net):
Uploading grafana_1.5.2~ppa1~trusty.dsc: done.
Uploading grafana_1.5.2~ppa1~trusty.orig.tar.gz: done.    
Uploading grafana_1.5.2~ppa1~trusty.debian.tar.gz: done.
Uploading grafana_1.5.2~ppa1~trusty_source.changes: done.
Successfully uploaded packages.
```
> Package grafana for trusty

- pkg/grafana/debian/changelog
- pkg/grafana/srcurl
Upgrade Grafana to version 1.9.1, which is the latest version in the 1.x
series.
This version includes the single stat panel, which I'd like to make use
of:
http://docs.grafana.org/reference/singlestat/
I haven't upgraded to version 2.x because it uses a new architecture
including a backend server which would require further changes; version
1.9.1 provides what I need for now.
These packages have successfully uploaded to the GOV.UK PPA.
> Upgrade Grafana to version 1.9.1

- pkg/gor/debian/changelog
- pkg/gor/debian/rules
For the recent package of Gor that was built `gor_0.10.1~ppa1_amd64.deb` the flag to set VERSION was not set during the build stage. This meant that we would have:
```
joshmyers@staging-cache-1:~$ gor --help
Version:
```
With this changes the new `gor_0.10.1~ppa2_amd64.deb` package has VERSION set:
```
vagrant@packager:~/packager$ gor --help
Version: 0.10.1
```
> Fix gor version

- pkg/gor/debian/changelog
- pkg/gor/srcurl
Gor 0.10.1 is replaying traffic but not the same
levels of traffic are hitting targets. Gor looks
to have had a significant rewrite from 0.7.X
(previous working version) and 0.10.X. Gor version
0.9.4 is the latest version which seems to give us
the same level of traffic replay. Downgrade to
this version now to get traffic replay working
again.
The first and second large peaks here are Gor@0.7.0, the smaller peaks are Gor releases just before 0.10.1. You can see that Gor 0.9.6 - 0.10.1 never seems to replay the same amount of traffic as 0.7.0. The last large peak on the right hand side is Gor@0.9.4, which is the most up to date release that gave us this "good" level of traffic replay, while also giving us the regex functionality `-output-http-url-regexp`
It should also be noted that with …
> Gor 0.10.1 is having issues, downgrade to 0.9.4.

- fpm/recipes/ruby-2.3.1/recipe.rb
We (@gpeng and I) temporarily made jenkins build from this branch (see: https://deploy.publishing.service.gov.uk/job/build_fpm_package/5/) and successfully installed ruby 2.3.1 from the resulting deb in a dev vm.
For https://github.com/alphagov/govuk-puppet/pull/4755 (or https://github.com/alphagov/govuk-puppet/pull/4651)
> Provide fpm recipe to build ruby 2.3.1

- fpm/recipes/rubygem-hiera-eyaml-gpg/recipe.rb
- fpm/recipes/rubygem-hiera-eyaml/recipe.rb
This creates the packages for both hiera-eyaml and hiera-eyaml-gpg. We previously packaged these up to go on PPA, but did not have them available for a Xenial release. This uses the built in fpm-cookery function to create a package directly from rubygems. The end result are packages called "rubygem-hiera-eyaml" and "rubygem-hiera-eyaml-gpg" respectively.
fpm functionality described here:
https://github.com/jordansissel/fpm/wiki/ConvertingGems
> Create packages for hiera-eyaml

- fpm/recipes/ruby-2.4.0/recipe.rb
ruby 2.4.0 was released on 2016-12-25. We should try and keep up to
date.
> Add a recipe to build ruby 2.4.0

- fpm/recipes/rubygem-hiera-eyaml-gpg/recipe.rb
- fpm/recipes/rubygem-hiera-eyaml/recipe.rb
The hiera-eyaml and hiera-eyaml-gpg packages were added for use in xenial but these are no longer needed as they will be installed using `gem install`
> Remove rubygem recipes

- fpm/recipes/terraform/recipe.rb
We use this for our current migration of GOV.UK to AWS, so would like to add a later version to CI.
> Add later version of Terraform

- fpm/Gemfile
- fpm/Gemfile.lock
Upgrade fpm to 1.9.2:
https://github.com/jordansissel/fpm/compare/v1.4.0...v1.9.2
Upgrade fpm-cookery to 0.32.0
https://github.com/bernd/fpm-cookery/compare/v0.31.0...v0.32.0
fpm-cookery v0.33.0 has a commit that breaks local sources, so for now
we are going to stay on 0.32.0:
https://github.com/bernd/fpm-cookery/commit/a3ac3345b11a559386e63d5a86799091ef968051
> Upgrade fpm and fpm-cookery gems

- fpm/recipes/logstash/README.md
- fpm/recipes/logstash/recipe.rb
Add recipe to package the Logstash jar file. The file is quite big,
so we are not going to include it in this repo. To create the package,
download the jar file from `https://logstash.objects.dreamhost.com/release/logstash-1.1.9-monolithic.jar`
to `/var/tmp/`.
This recipe won't run on Jenkins, run it locally and copy the file to
the Aptly machine.
> Add logstash 1.1.9

- fpm/recipes/ruby-2.2.8/recipe.rb
- fpm/recipes/ruby-2.3.5/recipe.rb
- fpm/recipes/ruby-2.4.2/recipe.rb
Security patches addressing: 
CVE-2017-0898: Buffer underrun vulnerability in Kernel.sprintf
CVE-2017-10784: Escape sequence injection vulnerability in the Basic authentication of WEBrick
CVE-2017-14033: Buffer underrun vulnerability in OpenSSL ASN1 docode
CVE-2017-14064: Heap exposure vulnerability in generating JSON
Multiple vulnerabilities in RubyGems
Updated bundled libyaml to version 0.1.7
[2.4.2](https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-4-2-released/)
[2.3.5](https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-3-5-released/)
[2.2.8](https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-2-8-released/)
> New rubies

- fpm/recipes/ruby-2.2.8/recipe.rb
- fpm/recipes/ruby-2.3.5/recipe.rb
- fpm/recipes/ruby-2.4.2/recipe.rb
The previous PR for these Ruby versions had the `.tar.gz` files but the `.tar.bz2` checksums. Unsurprisingly... that didn't work.
> Fix Ruby checksums

- fpm/recipes/etcdctl/recipe.rb
We run etcd in a container, but if we wish to interact with it we need the etcdctl binary.
This creates a package for this binary only, rather than the entirety of etcd itself.
This is related to the Firebreak work I've been doing on https://github.com/alphagov/govuk-puppet/pull/6589
> Add etcdctl

- fpm/recipes/ruby-2.5.0/recipe.rb
Ruby 2.5.0 was released 25-12-2017. I couldn't determine if any of the
library dependencies had changed so I used the same ones as 2.4.2.
> Add recipe for Ruby 2.5.0

- fpm/recipes/terraform/recipe.rb
We use 0.11.1 for the code when deploying to AWS. Upgrading to this package will enable us to test deploying using Jenkins.
> Upgrade Terraform to 0.11.1

- fpm/recipes/sops/recipe.rb
It appears when the binary is unpacked it is not executable. Add in a build step to ensure this is the case when it is packaged and installed on a system.
I have done this manually for now, but this should save anyone in the future.
> Make binary executable

- fpm/recipes/gds-local_pip-10.0.1/recipe.rb
- fpm/recipes/gds-local_python-2.7.14/recipe.rb
- fpm/recipes/gds-local_setuptools-39.0.1/recipe.rb
- The lastest Python version in Trusty does not support SSL/TLS as required
by the fetch search data Jenkins job, thus manually building and adding 2.7.14.
- This has been requested of GOV.UK infra by platform health.
Solo: @schmie
> Added recipes for a Python installation in /usr/local

- fpm/recipes/govuk-python-2.7.14/recipe.rb
- fpm/recipes/govuk-python-pip-10.0.1/recipe.rb
- fpm/recipes/govuk-python-setuptools-39.0.1/recipe.rb
- The lastest Python version in Trusty does not support SSL/TLS as required
by the fetch search data Jenkins job, thus manually building and adding 2.7.14.
- This has been requested of GOV.UK infra by platform health.
Solo: @schmie
> Added recipes for a Python installation in /opt

- fpm/.dockerignore
- fpm/Dockerfile.trusty
- fpm/Dockerfile.xenial
- fpm/Gemfile
- fpm/Gemfile.lock
- fpm/container-build.sh
Use Docker to provide consistent repeatable Ubuntu Trusty and Xenial build environments. This works on a recent Docker on macOS and would also work on a Linux build server with Docker installed.
> Build in containers

- fpm/recipes/awscli/recipe.rb
Package the most recent version (at this time) of the AWS CLI.
It's installed to `/opt/awscli` in a self-contained fashion with a Python 3 virtualenv, with a shim in `/usr/bin/aws`.
> Package the AWS CLI

- fpm/recipes/awscli/recipe.rb
This was a mistake - there is some native code in this package
> Don't set architecture: all on awscli package

- fpm/container-build.sh
`docker run -it` fails when running under Jenkins.
> Don't call docker with `-it` if not running in a TTY

- fpm/container-build.sh
Quoting the string seems to pass an empty string as an argument to the command, which breaks things
> Don't quote an empty string in shell script

- fpm/recipes/ruby-2.4.5/recipe.rb
- fpm/recipes/ruby-2.5.3/recipe.rb
This will allow us to run apps using the latest version of Ruby, which solves some security vulnerabilities.
Needed by https://github.com/alphagov/govuk-puppet/pull/8223
> Add recipes for Ruby 2.4.5 and 2.5.3

- fpm/recipes/prometheus-node-exporter-0.17.0/upstart-node-exporter.conf
Prometheus node-exporter by default runs on 9100, this is clashing with our
existing rabbitmq port, 9090 is used by garphite, so we are setting our
node-exporter to run on port 9080.
@ronocg <conor.glynn@digital.cabinet-office.gov.uk>
@jstandring-gds <julian.standring@digital.cabinet-office.gov.uk>
> trello-1899: node-exporter to run on 9080

- fpm/recipes/prometheus/recipe.rb
- fpm/recipes/prometheus/upstart-prometheus.conf
This builds the server package for prometheus.
With an upstart script, the prometheus.yml config file will be handled
by puppet when it installs this package.
@ronocg <conor.glynn@digital.cabinet-office.gov.uk>
@jstandring-gds <julian.standringn@digital.cabinet-office.gov.uk>
> Trello-1902: Build prometheus server pkg

- fpm/Dockerfile.trusty
** Context **
The following error happens when running docker build with the
Dockerfile.trusty build file. This could be addressed by changing the OS,
upgrading ruby or downgrading bundler.
```
ERROR:  Error installing bundler:
bundler requires Ruby version >= 2.3.0.
```
** Decision **
The goal is to get fpm builds working with docker. Changing the OS across the
estate or upgrading ruby for trusty will take considerably more effort than
downgrading the bundler version. So, ensure that bundler is a compatible
version by setting to `-v "< 2"`.
> Ensure bundler version works with trusty Ruby version

- fpm/Dockerfile.trusty
- fpm/Dockerfile.xenial
FPM Cookery requires git installed, this installs git
in to the continer.
It allows fpm cookery to clone git repos, configure things,
and inspect git repos.
Pair: @camdesgov & @smford
> Adding git to docker build image

- fpm/recipes/solr-6/init.solr
- fpm/recipes/solr-6/post-install
- fpm/recipes/solr-6/post-uninstall
- fpm/recipes/solr-6/recipe.rb
- fpm/recipes/solr-6/solr.in.sh
Lookie what I did.
https://trello.com/c/zLLNaKtv
A newer solr is going to be needed for CKAN 2.8 and I didn't want to continue the previous use-puppet-as-installer approach. We also are not tied to a fixed, single "core" anymore, which should make CI easier.
Tested on a vanilla trusty installation, appears to work. Default config and init script sourced from solr-6.4.2 release itself, not adding actual java dependency because our current package build system can't provide packages from 3rd party repos. The plan is to use puppet to enforce the dependency rather than redesign our build system.
Why not solr 8? CKAN isn't known to work on anything > 6.5.
> fpm: add solr-6 package

- fpm/recipes/ruby-2.7.1/recipe.rb
Adding recipe for Ruby 2.7.1 so we can upgrade gov uk apps to that version
> Add recipe for Ruby 2.7.1

- fpm/recipes/solr-6.6.2/init.solr
- fpm/recipes/solr-6.6.2/post-install
- fpm/recipes/solr-6.6.2/post-uninstall
- fpm/recipes/solr-6.6.2/recipe.rb
- fpm/recipes/solr-6.6.2/solr.in.sh
Add solr 6.6.2 version to be available for use with CKAN 2.8.3.
Most files copied over from solr-6 recipe, `solr.in.sh` has been updated.
> Add solr-6.6.2 fpm recipe

- fpm/recipes/govuk-python-3.6.12/recipe.rb
Allows python 3.6.12 to be available on trusty machine, executable installed under `/usr/bin/python3.6`
This is needed for use by CKAN 2.9 which has a minimum of python 3.6 as a requirement.
> Add python 3.6.12

- fpm/recipes/govuk-python-3.6.12/recipe.rb
Fix the naming to be in line with govuk-python 2.7.14 and also add in `libbz2-dev` needed by libraries like `pandas`, more detail here -
https://stackoverflow.com/questions/51149227/correctly-building-local-python3-with-bz2-support
> Fix the recipe to be in line with govuk-python 2.7.14

- fpm/recipes/prometheus/recipe.rb
So, so many new features and enhancements in the last two years...
https://github.com/prometheus/prometheus/blob/master/CHANGELOG.md
In particular, newer versions of prometheus support PromQL subqueries,
which make querying the metrics that router emits much cleaner.
We don't really use our prometheus all that much, so I think this is
fine to just ship-it-and-see.
> Upgrade prometheus from 2.6.0 to 2.23.0

- fpm/recipes/geos-3.9.0/recipe.rb
- fpm/recipes/postgresql-9.6-postgis-3.1/recipe.rb
- fpm/recipes/proj-4.9.3/recipe.rb
- fpm/recipes/sqlite-3/recipe.rb
This allows us to build a version of PostGIS that is compatible with Ubuntu Trusty, and uses a newer version of GDAL that is supported by Django 3.  Also includes a number of dependencies which are build as part of a chained recipe.
I've run this on a `ci-agent` machine and successfully built the Debian package for Ubuntu Trusty that [has been uploaded to our package server](https://apt.publishing.service.gov.uk/postgis/dists/trusty/main/binary-amd64/Packages).
Trello card: https://trello.com/c/BE3TN7De
> Add fpm recipe for PostGIS 3.1.1

- fpm/recipes/gdal-2.4.4/recipe.rb
It appears the syntax for fpm-cook has changed slightly, so updating to use the latest syntax.
Previously we built an almost empty Debian package containing only a CHANGELOG file. This change allows us to build the full package.
Trello card: https://trello.com/c/BE3TN7De
> Fix GDAL 2.4.4 build

- fpm/recipes/geos-3.9.0/recipe.rb
- fpm/recipes/postgresql-9.6-postgis-3.1/recipe.rb
- fpm/recipes/proj-4.9.3/recipe.rb
- fpm/recipes/sqlite-3/recipe.rb
It appears the syntax for fpm-cook has changed slightly, so updating to use the latest syntax.
Previously we built an almost empty Debian package containing only a CHANGELOG file. This change allows us to build the full package.
I've deposited the built Debian package into [our Apt server](https://apt.publishing.service.gov.uk/postgis/dists/trusty/main/binary-amd64/Packages) which shows a considerably larger size than the previous <1kb file :see_no_evil:.
Trello card: https://trello.com/c/BE3TN7De
> Fix PostGIS 3.1.1 build

- README.md
- test-your-package/Dockerfile
The developer VM has gone away, but the instructions we have for
testing whether a generated package works, relies on the dev VM:
https://github.com/alphagov/govuk-developer-docs/blob/17deefd6068ff955d14c8dbe641d5b5a0dbe66fa/source/manual/debian-packaging.html.md?plain=1#L136-L150
I've found an equivalent way of testing that the package works,
using Docker, which is the technology we've moved onto.
Trello: https://trello.com/c/ZMrLumn8/2837-upgrade-ruby-for-our-apps-5
> Document how to test a created package
